✨ [FEAT] CreateMain -> CreateEdit 이미지 전달
THE-SOPT-Joint-Seminar-ZEPETO/ZEPETO-iOS pull request #10
Opened 2022-05-20 14:55 UTC by wngus4296

## 🍎 관련 이슈
closed #9 

## 🍎 변경 사항 및 이유
- CreateMain의 imagePicker로 가져온 이미지를 CreateEdit 뷰에 전달해서 띄웠습니다.
- imagePicker 창 dismiss하면서 CreateEdit뷰 present 하였습니다.

## 🍎 PR Point
- 시뮬 돌려보면 fullscreen이 제대로 먹는데 녹화하면 위에 빈공간이 남아보이네요 허허

## 📸 ScreenShot
![Simulator Screen Recording - iPhone 11 - 2022-05-20 at 20 31 29](https://user-images.githubusercontent.com/58043306/169554173-86f9d4c1-d213-4a4d-888b-ad8f06832674.gif)

2022-05-21 04:16 UTC, jane1choi requested changes
컨벤션 관련한 것만 수정하면 될 것 같네요!
코드도 깔끔해지고 굿굿!! 수고했어요🔥

2022-05-21 04:16 UTC, jane1choi commented on ZEPETO-iOS/ZEPETO-iOS/Screen/CreateMain/VC/CreateMainVC.swift
>          if let image = info[UIImagePickerController.InfoKey.originalImage] as? UIImage{
컨벤션에 따라 `UIImage{`사이에 공백 한칸 줍시다!

2022-05-21 04:16 UTC, jane1choi commented on ZEPETO-iOS/ZEPETO-iOS/Screen/CreateMain/VC/CreateMainVC.swift
> +        dismiss(animated: false) {
`self.`붙여줍시다! 
`completion handler`로 처리 잘해줬네요🔥 굿굿👍🏻

2022-05-21 04:33 UTC, jeongkite submitted a review, later dismissed
깔꼼한 코드 잘 봤슴다👍👍 최고네요~~~

2022-05-21 04:33 UTC, jeongkite commented on ZEPETO-iOS/ZEPETO-iOS/Screen/CreateMain/VC/CreateMainVC.swift
>          if let image = info[UIImagePickerController.InfoKey.originalImage] as? UIImage{
옹 imagePicker로 가져온 이미지를 이렇게 넣는거군요! 하나 배워갑니다~~✨

2022-05-21 16:26 UTC, jeongkite approved these changes, later dismissed

2022-05-23 19:39 UTC, jane1choi approved these changes
어푸룹! 수고해써🔥

2022-05-24 03:54 UTC, jeongkite approved these changes
완벽한 리뷰 반영.. 최곱니당 👍

2022-05-24 03:55 UTC, merged