✨ [FEAT] UI feed 뷰 구성
THE-SOPT-Joint-Seminar-ZEPETO/ZEPETO-iOS pull request #12
Opened 2022-05-22 04:31 UTC by jeongkite

## 🍎 관련 이슈
closed #4 

## 🍎 변경 사항 및 이유
- Feed detail 뷰를 작업했습니다.
- 더보기/숨기기 구현했습니다.

## 🍎 PR Point
- API 명세에 좋아요와 댓글 수 데이터를 주지 않아 아이콘 아래 숫자까지 이미지로 넣었습니다 (수정해야한다면 하겟습니다..)

## 📸 ScreenShot
![Simulator Screen Recording - iPhone 13 mini - 2022-05-22 at 13 30 41](https://user-images.githubusercontent.com/75439868/169678700-fecb97c4-0acc-4891-a1c8-b113f9bb1a1a.gif)

2022-05-22 08:24 UTC, jane1choi requested changes
그냥 천재네....
알잘딱깔센,,내가 도와줄게 없어 그냥!!
넘 수고했고 리뷰 한번만 확인해주세요😊😊

2022-05-22 08:24 UTC, jane1choi commented on ZEPETO-iOS/ZEPETO-iOS/Screen/Feed/VC/FeedVC.swift
> +    @IBOutlet weak var usernameTextLabel: UILabel!
요기 `userNameLabel` 요런 네이밍이 컨벤션에도 맞고 더 명시적일 것 같아요~!

2022-05-22 08:24 UTC, jane1choi commented on ZEPETO-iOS/ZEPETO-iOS/Screen/Feed/VC/FeedVC.swift
> +    @IBOutlet weak var mainTextLabel: UILabel!
요기도 내용에 관련된거라면 `mainContentLabel` 요런식으로? 바꿔봐도 좋을 것 같네요!

2022-05-22 08:24 UTC, jane1choi commented on ZEPETO-iOS/ZEPETO-iOS/Screen/Feed/VC/FeedVC.swift
> +        sender.isSelected = !sender.isSelected
요부분 잘했는데! 만약 버튼을 터치할 때마다 `isSelected` 상태를 반전시켜주고 싶은거라면 
Bool 값을 반전 시켜주는 메서드인 `toggle()` 을 활용해도 됩니다!
`isSelected.toggle()` 요런식으로!
요부분은 바꾸진 않아도 되고 이 방법도 있구나 정도로 참고만 해주세요~!

2022-05-22 08:24 UTC, jane1choi commented on ZEPETO-iOS/ZEPETO-iOS/Screen/Feed/VC/FeedVC.swift
> +        configMainTextLabelShort()
요함수 configUI() 함수 안에서 말고 viewDidLoad()에서 따로 호출해주는거 어떨까요~?

2022-05-22 08:24 UTC, jane1choi commented on ZEPETO-iOS/ZEPETO-iOS/Screen/Feed/VC/FeedVC.swift
> +
우리 프로젝트에서 extension 파일을 만들어서 따로 관리하고 있으니,
이부분은 UILabel+ 라는 파일로 옮겨주세요!

2022-05-22 08:24 UTC, jane1choi commented on ZEPETO-iOS/ZEPETO-iOS/Screen/Feed/VC/FeedVC.swift
> +        }
요기 함수들 다 UI 구성에 관한 것들이라면 // Mark: - UI로 위치를 옮기는 건 어떨까요??

2022-05-22 08:24 UTC, jane1choi commented on ZEPETO-iOS/ZEPETO-iOS/Screen/Feed/VC/FeedVC.swift
> +    }
요부분 뷰가 나타날 때 마다 버튼을 숨기려고 해준 것 같은데 viewDidAppear()에서 잘해줬네요! 
근데 config랑 hide가 둘다 동사이니 `hideMoreBtn` 요런 네이밍이 더 직관적일 것 같아요!
저도 변수, 함수명 네이밍이 항상 고민인데 연습하면서 더 직관적인 네이밍에 대해 고민해봅시다!
그리구 컨벤션 맞춰서 위에 함수랑 한줄만 띄워줍시다..ㅎ

2022-05-23 13:48 UTC, wngus4296 requested changes
코드 깔끔하네요!! 고생하셨습니다 🔥
viewDidLoad에 코멘트 부분 확인 한 번 해주세요! 그냥 저의 개인 적인 생각일 뿐이니,,, 변경하지 않으셔도 됩니다,,

+ 추가로 은주언니 코멘트 중에 FeedVC viewDidLoad랑 viewDidAppear 사이에 빈 줄 넣는 거 아직 반영 안된 것 같아서 수정 부탁드립니당

2022-05-23 13:48 UTC, wngus4296 commented on ZEPETO-iOS/ZEPETO-iOS/Global/Extension/UILabel+.swift
> +    }
우와... 이거 신기하네요

2022-05-23 13:48 UTC, wngus4296 commented on ZEPETO-iOS/ZEPETO-iOS/Screen/Feed/VC/FeedVC.swift
> +        mainContentLabel.textDropShadow()
이 두 줄도 하나의 함수로 빼는 건 어떤가요?! 물론 개인 스타일입니다!!!!!!

2022-05-23 13:48 UTC, wngus4296 commented on ZEPETO-iOS/ZEPETO-iOS/Screen/Feed/VC/FeedVC.swift
> +        sender.isSelected.toggle()
굳굳

2022-05-23 19:43 UTC, jane1choi commented on ZEPETO-iOS/ZEPETO-iOS/Screen/Feed/VC/FeedVC.swift
> +        mainContentLabel.textDropShadow()
내가 요부분 확인을 못했었네,, 주현이 말처럼 함수에 넣는게 좋겠다! 
UI에 관련된거니까 `configUI()` 함수안에다 넣어줍시다!
생명주기 함수안에는 함수호출만 해줍시다~!

2022-05-23 19:45 UTC, jane1choi requested changes
수정사항 잘 확인했어요!!
~~~Swift
userNameLabel.textDropShadow()
mainContentLabel.textDropShadow()
~~~

요부분만 `configUI()` 함수 안에다 넣어주자!

2022-05-23 19:45 UTC, jane1choi commented on ZEPETO-iOS/ZEPETO-iOS/Screen/Feed/VC/FeedVC.swift
> +        sender.isSelected.toggle()
리뷰 반영 모야 굿굿👍🏻

2022-05-24 04:02 UTC, wngus4296 approved these changes
리뷰 반영 확인했습니다 👍 고생했어요!!

2022-05-24 04:25 UTC, jane1choi approved these changes
화긴이여~👍🏻

2022-05-24 05:01 UTC, merged