✨ [FEAT] 게시글 작성 API 연결
THE-SOPT-Joint-Seminar-ZEPETO/ZEPETO-iOS pull request #20
Opened 2022-06-02 01:00 UTC by jane1choi

## 🍎 관련 이슈
closed #19 

## 🍎 변경 사항 및 이유
- 게시글 작성 API를 연결했습니다.

## 🍎 PR Point
- 이미지 업로드를 위해 multipart/form-data 형식으로 통신해주었습니다.
- FeedVC에서 notificationCenter를 이용해 이미지 데이터를 받던 부분은 서버요청으로 바뀔 부분이라 필요없는 코드를 삭제 해주었습니다.
**+** 노션에 적혀있는 명세서랑 res가 다르니 꼭 PostMan으로 확인 후에 작업해주세요!

## 📸 ScreenShot
![Simulator Screen Recording - iPhone 11 - 2022-06-02 at 09 58 41](https://user-images.githubusercontent.com/63277563/171525405-9740d65e-b95e-4535-b504-4505d82f4313.gif) <img width="500" alt="스크린샷 2022-06-02 오전 9 57 22" src="https://user-images.githubusercontent.com/63277563/171525261-ade15af9-be33-450a-9bbd-d5da397754f2.png">

2022-06-02 10:16 UTC, wngus4296 requested changes
서버 통신 깔끔하게 정리해주셔서 도움 많이 되었습니다! 고생하셨어요 👍🏻👍🏻
주석이랑 import 코드리뷰 한 번 확인해주세요 !!

2022-06-02 10:16 UTC, wngus4296 commented on ZEPETO-iOS/ZEPETO-iOS/Network/Services/FeedService.swift
>          }
감사합니다 멀티파트폼.. 배워갑니다... 🥹

2022-06-02 10:16 UTC, wngus4296 commented on ZEPETO-iOS/ZEPETO-iOS/Screen/CreateUpload/VC/CreateUploadVC.swift
> +// MARK: Network
// MARK: - Network 는 어떨까요 ~!

2022-06-02 10:16 UTC, wngus4296 commented on ZEPETO-iOS/ZEPETO-iOS/Network/Services/FeedService.swift
원래 있던 코드이긴 한데 `import Foundation`은 지우는 것이 어떨까여!!!

2022-06-02 10:16 UTC, wngus4296 commented on ZEPETO-iOS/ZEPETO-iOS/Network/Services/FeedService.swift
FeedAPI.swift 파일에도 지우면 좋을 것 같아요 🙃

2022-06-02 12:23 UTC, jane1choi commented on ZEPETO-iOS/ZEPETO-iOS/Screen/CreateUpload/VC/CreateUploadVC.swift
> +// MARK: Network
아 왜이렇게 했지,, 고칠게여~

2022-06-02 12:28 UTC, jane1choi commented on ZEPETO-iOS/ZEPETO-iOS/Network/Services/FeedService.swift
@wngus4296 
https://developer.apple.com/documentation/foundation#//apple_ref/doc/uid/20001091
Foundation에 대해서 위의 공식문서 참고해보면 알겠지만, Foundation은 네트워킹, 날짜 및 시간, 텍스트 가공 등에 필요한 프레임워크입니다!

2022-06-02 13:09 UTC, wngus4296 commented on ZEPETO-iOS/ZEPETO-iOS/Network/Services/FeedService.swift
UIKit이 Foundation을 import하고 있기 때문에 UIKit만 써줘도 된다고 생각했는데 혹쉬.. 틀린 걸까요 🥹

2022-06-02 14:26 UTC, jane1choi commented on ZEPETO-iOS/ZEPETO-iOS/Network/Services/FeedService.swift
@wngus4296 아하! 그뜻이었구나,, 쏴리,, 맞네맞네 얼릉 고칠게여~!

2022-06-02 14:52 UTC, wngus4296 approved these changes
확인했습니다!! 고생 많았어요 ❤️‍🔥

2022-06-02 15:36 UTC, jeongkite approved these changes
짱짱 선배님의 코드.. 잘 보고 배워갑니다!!!

2022-06-02 15:36 UTC, jeongkite commented on ZEPETO-iOS/ZEPETO-iOS/Network/Services/FeedService.swift
>          }
옹 요골 요로코롬.. 멋진 코드 배워갑니다!

2022-06-02 15:36 UTC, jeongkite commented on ZEPETO-iOS/ZEPETO-iOS/Network/APIManagers/FeedAPI.swift
> +    /// [POST] 게시글 작성
GET/POST는 주석 작성시 요렇게 대괄호 안에 넣어주는게 일반적인가요?! 주현이 코드도 이런식으로 되어있어 일반적인 규칙인지 궁금합니다!

2022-06-03 01:51 UTC, jane1choi commented on ZEPETO-iOS/ZEPETO-iOS/Network/APIManagers/FeedAPI.swift
> +    /// [POST] 게시글 작성
그냥 저의 스타일...이긴 한데 메소드 써주면 한눈에 잘 들어와서 이렇게 써주고 있습니다!

2022-06-03 01:52 UTC, merged