✨ [FEAT] 메인 조회 서버 연결
THE-SOPT-Joint-Seminar-ZEPETO/ZEPETO-iOS pull request #22
Opened 2022-06-02 10:25 UTC by wngus4296

## 🍎 관련 이슈
closed #18 

## 🍎 변경 사항 및 이유
만들기 메인 이미지 조회 API를 연결하였습니다.

## 🍎 PR Point
⚠️  podfile에 Kingfisher추가했습니다. 나중에 머지 후 `pod install` 필요합니다!!

기절할 뻔 했네요

## 📸 ScreenShot
![Simulator Screen Recording - iPhone 11 - 2022-06-02 at 19 23 58](https://user-images.githubusercontent.com/58043306/171609920-7a2713d0-b1ed-4d06-a8a1-037b0a4e653f.gif) <img width="428" alt="image" src="https://user-images.githubusercontent.com/58043306/171608980-298b8495-c2cd-4903-8f79-dfabcd3b603b.png">

2022-06-02 12:40 UTC, jane1choi requested changes
수고했어열...뭐..지적할게 없네여......
대체 못하는게 뭔지...🤔리뷰 한번만 확인해주셔라...

2022-06-02 12:40 UTC, jane1choi commented on ZEPETO-iOS/Podfile
> +  pod 'Kingfisher'
굿굿👍🏻 안알려줘도,,,,잘하네여,,,짱이다 진짜,,,

2022-06-02 12:40 UTC, jane1choi commented on ZEPETO-iOS/ZEPETO-iOS/Network/Services/MainService.swift
> +    case imagesGet
동사+목적어 이렇게 getImages가 더 좋은 네이밍이라고 개인적으로 생각합니다..!
(네이밍에서 서버의 향기가 느껴지네여ㅋㅋㅋ)

2022-06-02 12:40 UTC, jane1choi commented on ZEPETO-iOS/ZEPETO-iOS/Screen/CreateMain/Cell/CVC/ImgCVC.swift
> +        contentImgView.kf.setImage(with: imageUrl)
굿굿굿!!

2022-06-02 12:40 UTC, jane1choi commented on ZEPETO-iOS/ZEPETO-iOS/Screen/CreateMain/VC/CreateMainVC.swift
> +                    }
비동기처리까지....대체 못하는게 모야......?????? 
너 진짜 천재다.....

2022-06-02 12:40 UTC, jane1choi commented on ZEPETO-iOS/ZEPETO-iOS/Network/APIManagers/MainAPI.swift
> +
요기 import Foundation 추가해줍시다!

2022-06-02 13:10 UTC, wngus4296 commented on ZEPETO-iOS/Podfile
> +  pod 'Kingfisher'
킹킹피셔 ~

2022-06-02 13:10 UTC, wngus4296 commented on ZEPETO-iOS/ZEPETO-iOS/Network/Services/MainService.swift
> +    case imagesGet
ㅋㅋㅋㅋㅋㅋㅋㅋ 서버... 에 너무 익숙해져있네요... 네이밍 한 번 쫙 보면서 적절하게 수정 해보겠습니다 !!!

2022-06-02 19:49 UTC, jeongkite requested changes
진짜 이게 아요 와비가 맞나..? 경력직은 역시 다르네여... 짱!!!!

2022-06-02 19:49 UTC, jeongkite commented on ZEPETO-iOS/ZEPETO-iOS/Screen/CreateMain/Cell/CVC/ImgCVC.swift
> +        contentImgView.kf.setImage(with: imageUrl)
왕 kingfisher까지..!! 저두 인스타 클론코딩에 함 적용해봐야겠어요!!!

2022-06-02 19:49 UTC, jeongkite commented on ZEPETO-iOS/ZEPETO-iOS/Screen/CreateMain/VC/CreateMainVC.swift
> +                    }
이게 아요 와이비가 맞나..? 벽이 느껴지네요.. 완벽.....✨

2022-06-02 19:49 UTC, jeongkite commented on ZEPETO-iOS/ZEPETO-iOS/Network/APIModels/MainImagesGetResModel.swift
> +    let profileImage: String
요거 profileImage도 위에 친구들이랑 동일하게 String인데 가독성 때문에 따로 뺴준건가요?!

2022-06-02 19:49 UTC, jeongkite commented on ZEPETO-iOS/ZEPETO-iOS/Network/APIManagers/MainAPI.swift
> +                print(data)
요 프린트문 데이터 넘어오는지 확인하려고 넣어준거면 삭제하는게 좋을 것 같아요!

2022-06-03 01:02 UTC, wngus4296 commented on ZEPETO-iOS/ZEPETO-iOS/Network/APIModels/MainImagesGetResModel.swift
> +    let profileImage: String
어라라 ~ 그런 건 아니었는데 머쓱하네요 수정하겠습니다 🙃

2022-06-03 01:53 UTC, jane1choi commented on ZEPETO-iOS/ZEPETO-iOS/Network/APIManagers/MainAPI.swift
> +                print(data)
@jeongkite 예리하돠 예리해..!

2022-06-03 01:55 UTC, jane1choi commented on ZEPETO-iOS/ZEPETO-iOS/Screen/CreateMain/VC/CreateMainVC.swift
> +        imagesGet()
요기도 getImages() 이런식으로 바꾸면 직관적으로 이미지 받아오는 함수구나 알 수 있어서 주석 삭제해도 될 것 같아! 
주석지우고 공백도 삭제해주자!!

2022-06-03 01:59 UTC, wngus4296 commented on ZEPETO-iOS/ZEPETO-iOS/Screen/CreateMain/VC/CreateMainVC.swift
> +        imagesGet()
오 네넹

2022-06-03 02:10 UTC, jane1choi submitted a review, later dismissed
어푸룹 쾅!! 수고했어여~!!

2022-06-03 04:36 UTC, jeongkite approved these changes
빠른 수정 최고네요우~~👍

2022-06-03 05:12 UTC, merged